### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by tonypeng** [chenglou/bootstrap-everywhere.safariextension#3]
steps to repro:
1. go to mit.edu/6.01
2. press B button
3. does not work

needs more flexbox imho

**Comment by chenglou** [comment]
The site already has quite a bit of basic CSS resets, which override bootstrap's defaults. The defaults here won't change much anyway as the styles are visually pretty similar.

What it does do is to turn the site a bit more responsive. To test, resizing your window and see it snaps at appropriate widths. Although here it's debatable whether the width is more appropriate than without the responsiveness.

Here's a page that works a bit better: http://web.mit.edu/6.033/www/materials.shtml
