### ISSUE TITLE
Add a gif of an example for those using non-Steve-Jobs-approved OSes or mobile browsers

### ISSUE THREAD

**Issue by AaronHarris** [chenglou/bootstrap-everywhere.safariextension#4]
So we can appreciate your work too

**Comment by chenglou** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1909539/12603292/62535312-c47f-11e5-9215-322bcff5bea6.gif)

Added to README. Had to remove sensitive names. You get extra mention for making me go to this length.

**Comment by AaronHarris** [comment]
Very cool.
